<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{bb009617-2d4f-4999-a2b9-f4b71b49f1b6}" SpecialFunc="None">
    <Declaration><![CDATA[VAR
    bStatus : BOOL := FALSE; // or TRUE
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>